plugins:
  libvirt:
    executor: central_deployment_agent
    package_name: cloudify-libvirt-plugin
    package_version: '0.5.0'
    source: https://github.com/cloudify-incubator/cloudify-libvirt-plugin/archive/0.5.0.zip

data_types:

  network_params:
    properties:
      use_external_resource:
        required: false
        default: false
        description: >
          Use external object. The default is `false`.
      resource_id:
        required: false
        default: ""
        description: >
          Used to identify the object when `use_external_resource` is true.
      dev:
        required: false
        default: ""
        description: >
          Device name
      forwards:
        required: false
        default: []
        description: >
          Settings for network `forwards`.
      ips:
        required: false
        default: []
        description: >
          Settings for network `ips`.

  domain_params:
    properties:
      vcpu:
        required: false
        type: integer
        description: >
          CPU count
      memory_minsize:
        required: false
        type: integer
        description: >
          Recomended VM memory size in KiB for downgrade
      memory_size:
        required: false
        type: integer
        description: >
          VM memory size in KiB
      nvram:
        required: false
        type: string
        description: >
          Path to nvram
      disks:
        required: false
        description: >
          List connected disks
        default: []
      networks:
        required: false
        description: >
          List connected networks
        default: []
      full_dump:
        default: false
        description: >
          Make full dump for backups with memory snapshot to dump file.
          On create/restore backup will be removed all snapshots in domain.
      wait_for_ip:
        default: true
        description: >
          Wait until we have some private ip on interfaces
      domain_type:
        description: >
          Type of virtualization
        default: qemu

node_types:

  cloudify.libvirt.domain:
    derived_from: cloudify.nodes.Compute
    properties:
      backup_dir:
        default: './'
      libvirt_auth:
        default: 'qemu:///system'
      params:
        type: domain_params
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: libvirt.cloudify_libvirt.domain_tasks.create
          inputs: {}
        configure:
          implementation: libvirt.cloudify_libvirt.domain_tasks.configure
          inputs: {}
        start:
          implementation: libvirt.cloudify_libvirt.domain_tasks.start
          inputs: {}
        reboot:
          implementation: libvirt.cloudify_libvirt.domain_tasks.reboot
          inputs: {}
        stop:
          implementation: libvirt.cloudify_libvirt.domain_tasks.stop
          inputs: {}
        delete:
          implementation: libvirt.cloudify_libvirt.domain_tasks.delete
          inputs: {}
      # suspend/resume
      cloudify.interfaces.freeze:
        suspend:
          implementation: libvirt.cloudify_libvirt.domain_tasks.suspend
          inputs: {}
        resume:
          implementation: libvirt.cloudify_libvirt.domain_tasks.resume
          inputs: {}
      # backups related section
      cloudify.interfaces.snapshot:
        create:
          implementation: libvirt.cloudify_libvirt.domain_tasks.snapshot_create
          inputs: {}
        apply:
          implementation: libvirt.cloudify_libvirt.domain_tasks.snapshot_apply
          inputs: {}
        delete:
          implementation: libvirt.cloudify_libvirt.domain_tasks.snapshot_delete
          inputs: {}
      # usage
      cloudify.interfaces.statistics:
        perfomance:
          implementation: libvirt.cloudify_libvirt.domain_tasks.perfomance
          inputs: {}

  cloudify.libvirt.network:
    derived_from: cloudify.nodes.Network
    properties:
      backup_dir:
        default: './'
      libvirt_auth:
        default: 'qemu:///system'
      params:
        type: network_params
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: libvirt.cloudify_libvirt.network_tasks.create
          inputs: {}
        delete:
          implementation: libvirt.cloudify_libvirt.network_tasks.delete
          inputs: {}
      # backups related section
      cloudify.interfaces.snapshot:
        create:
          implementation: libvirt.cloudify_libvirt.network_tasks.snapshot_create
          inputs: {}
        apply:
          implementation: libvirt.cloudify_libvirt.network_tasks.snapshot_apply
          inputs: {}
        delete:
          implementation: libvirt.cloudify_libvirt.network_tasks.snapshot_delete
          inputs: {}

relationships:

  cloudify.libvirt.relationships.connected_to:
    derived_from: cloudify.relationships.connected_to
    target_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        establish:
          implementation: libvirt.cloudify_libvirt.network_tasks.link
          inputs: {}
        unlink:
          implementation: libvirt.cloudify_libvirt.network_tasks.unlink
          inputs: {}
