plugins:
  libvirt:
    executor: central_deployment_agent
    source: https://github.com/0lvin-cfy/cloudify-libvirt-plugin/archive/master.zip
    package_name: cloudify-libvirt-plugin
    package_version: '0.1'

node_types:

  cloudify.libvirt.domain:
    derived_from: cloudify.nodes.Root
    properties:
      libvirt_auth:
        default:
          url: 'qemu:///system'
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: libvirt.cloudify_libvirt.domain_tasks.create
          inputs: {}
        configure:
          implementation: libvirt.cloudify_libvirt.domain_tasks.configure
          inputs: {}
        start:
          implementation: libvirt.cloudify_libvirt.domain_tasks.start
          inputs: {}
        stop:
          implementation: libvirt.cloudify_libvirt.domain_tasks.stop
          inputs: {}
        delete:
          implementation: libvirt.cloudify_libvirt.domain_tasks.delete
          inputs: {}

  cloudify.libvirt.network:
    derived_from: cloudify.nodes.Root
    properties:
      libvirt_auth:
        default:
          url: 'qemu:///system'
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: libvirt.cloudify_libvirt.network_tasks.create
          inputs: {}
        configure:
          implementation: libvirt.cloudify_libvirt.network_tasks.configure
          inputs: {}
        start:
          implementation: libvirt.cloudify_libvirt.network_tasks.start
          inputs: {}
        stop:
          implementation: libvirt.cloudify_libvirt.network_tasks.stop
          inputs: {}
        delete:
          implementation: libvirt.cloudify_libvirt.network_tasks.delete
          inputs: {}

