plugins:
  libvirt:
    executor: central_deployment_agent
    source: https://github.com/0lvin-cfy/cloudify-libvirt-plugin/archive/master.zip
    package_name: cloudify-libvirt-plugin
    package_version: '0.1'

node_types:

  cloudify.libvirt.domain:
    derived_from: cloudify.nodes.Compute
    properties:
      libvirt_auth:
        default:
          url: 'qemu:///system'
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: libvirt.cloudify_libvirt.domain_tasks.create
          inputs: {}
        configure:
          implementation: libvirt.cloudify_libvirt.domain_tasks.configure
          inputs: {}
        suspend:
          implementation: libvirt.cloudify_libvirt.domain_tasks.suspend
          inputs: {}
        resume:
          implementation: libvirt.cloudify_libvirt.domain_tasks.resume
          inputs: {}
        stop:
          implementation: libvirt.cloudify_libvirt.domain_tasks.stop
          inputs: {}
        delete:
          implementation: libvirt.cloudify_libvirt.domain_tasks.delete
          inputs: {}

  cloudify.libvirt.network:
    derived_from: cloudify.nodes.Network
    properties:
      libvirt_auth:
        default:
          url: 'qemu:///system'
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: libvirt.cloudify_libvirt.network_tasks.create
          inputs: {}
        delete:
          implementation: libvirt.cloudify_libvirt.network_tasks.delete
          inputs: {}

relationships:

  cloudify.libvirt.relationships.connected_to:
    derived_from: cloudify.relationships.connected_to
    target_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        postconfigure:
          implementation: libvirt.cloudify_libvirt.network_tasks.link
          inputs: {}
        unlink:
          implementation: libvirt.cloudify_libvirt.network_tasks.unlink
          inputs: {}

workflows:
  suspend: libvirt.cloudify_libvirt.workflows.suspend
  resume: libvirt.cloudify_libvirt.workflows.resume
